### ISSUE TITLE
Cannot install modules due to error with PYTHON variable is missing

### ISSUE THREAD

**Issue by ematseruk** [epam/sitecore-engx-scaffold#27]
**Steps to reproduce**
1. Clone the repo
2. Execute `npm i`
3. Observe the problem:

> deasync@0.1.10 install C:\workspace\.repo\sitecore-engx-scaffold\node_modules\deasync
> node ./build.js
>C:\workspace\.repo\sitecore-engx-scaffold\node_modules\deasync>if not defined >npm_config_node_gyp (node >"C:\Users\Yauheni_Matseruk\AppData\Roaming\nvm\v12.3.1\node_modules\npm\node_modules\>npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node >"C:\Users\Yauheni_Matseruk\AppData\Roaming\nvm\v12.3.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
>gyp ERR! configure error
>gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
>gyp ERR! stack     at PythonFinder.failNoPython >(C:\Users\Yauheni_Matseruk\AppData\Roaming\nvm\v12.3.1\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Yauheni_Matseruk\AppData\Roaming\nvm\v12.3.1\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\Yauheni_Matseruk\AppData\Roaming\nvm\v12.3.1\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:149:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Yauheni_Matseruk\\AppData\\Roaming\\nvm\\v12.3.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\workspace\.repo\sitecore-engx-scaffold\node_modules\deasync
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.10 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.10 install script.

It seems that the issue is fixed in the latest version of `deasync`, but in order to resolve it requires update of modules.
https://github.com/abbr/deasync/issues/106

**Comment by AndriyZyakun** [comment]
This issue related to the version of node.js. Based on your log you have version 12.3.1.  Version 11.15.0 is the latest working version with node-gyp. You have to change node.js version to make away the issue.
